version:  '3.7'
services:
  mysql:
    image: mysql:8.0
    restart: on-failure
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony 
    volumes:
      - './my-datavolume:/var/lib/mysql'

  nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      # - './apps/my-symfony-app/public/:/usr/src/app'
      # - './apps/my-symfony-app/public:/usr/src/app/public'
      - './apps/my-symfony-app/public:/usr/src/app'
      - './docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    ports:
      - '80:80'
    depends_on:
     - php
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    restart: on-failure
    volumes:
      - './apps/my-symfony-app:/usr/src/app'
    env_file:
      - .env
 